# Generated by Django 6.0.6 on 2026-07-10 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0002_deckassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckassignment',
            name='break_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deckassignment',
            name='break_time_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='deckassignment',
            name='on_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deckassignment',
            name='pool_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='meet',
            name='course_type',
            field=models.CharField(choices=[('SCY', 'SCY — Short Course Yards'), ('SCM', 'SCM — Short Course Meters'), ('LCM', 'LCM — Long Course Meters')], default='SCY', max_length=10),
        ),
        migrations.AddField(
            model_name='meet',
            name='has_relay_events',
            field=models.BooleanField(default=False, help_text='Does this meet include relay events?'),
        ),
        migrations.AddField(
            model_name='meet',
            name='num_pools',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='session',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='has_relay_starts',
            field=models.BooleanField(default=False, help_text='Does this session include relay starts?'),
        ),
        migrations.AddField(
            model_name='session',
            name='offline_mode',
            field=models.BooleanField(default=False, help_text='Enable for venues with limited internet access'),
        ),
        migrations.AddField(
            model_name='session',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('ended', 'Ended')], default='not_started', max_length=20),
        ),
        migrations.CreateModel(
            name='VolunteerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_logs', to='meets.session')),
            ],
            options={
                'unique_together': {('session', 'official')},
            },
        ),
    ]
